wandb_version: 1

lr:
  desc: null
  value: 0.0001
batch_size:
  desc: null
  value: 2
data_path:
  desc: null
  value: data/npy/CT_Abd
model_type:
  desc: null
  value: vit_b
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1713809508.0
    t:
      1:
      - 1
      - 41
      - 48
      - 55
      2:
      - 1
      - 41
      - 48
      - 55
      3:
      - 16
      - 23
      4: 3.10.14
      5: 0.16.6
      8:
      - 4
      - 5
      13: darwin-arm64
